upkoding/account/urls.py
from django.urls import path, include

from . import views

app_name = 'account'

urlpatterns = [
    path('login/', views.LoginView.as_view(), name='login'),
    path('logout/', views.LogoutView.as_view(), name='logout'),
    path('settings/', views.SettingsView.as_view(), name='settings'),
    # complete namespace: account:social
    path('', include('social_django.urls', namespace='social')),
]

upkoding/base/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic.base import TemplateView

from .views import render_template, Index

app_name = 'base'


urlpatterns = [
    path('', Index.as_view(), name='index'),
    path('diskusi/', render_template('base/forum.html'), name='forum'),
    path('tentang/', render_template('base/tentang.html'), name='tentang'),
    path('robots.txt', render_template('base/robots.txt', 'text/plain')),
]

upkoding/coders/urls.py
from django.urls import path

from . import views

app_name = 'coders'

urlpatterns = [
    path('<str:username>/', views.CoderDetail.as_view(), name='detail'),
    path('', views.CoderList.as_view(), name='list'),
]

upkoding/upkoding/urls.py
from django.conf import settings
from django.contrib import admin
from django.http.response import HttpResponse
from django.urls import path, include
from django.contrib.staticfiles.urls import static


def appengine_warmup(request):
    return HttpResponse('ok')


urlpatterns = [
    path('admin/', admin.site.urls),
    path('account/', include('account.urls', namespace='account')),
    path('proyek/', include('projects.urls', namespace='projects')),
    path('coders/', include('coders.urls', namespace='coders')),
    path('_ah/warmup/', appengine_warmup),
    path('', include('base.urls', namespace='base')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

upkoding/base/models.py
from django.db import models

# Create your models here.

upkoding/base/views.py
from django.views.generic.base import TemplateView

from projects.models import Project, UserProject


def render_template(name, content_type="text/html; charset=utf-8"):
    """
    Just a shortcuts method.
    """
    return TemplateView.as_view(template_name=name, content_type=content_type)


class Index(TemplateView):
    template_name = 'base/index.html'

    def get_context_data(self, **kwargs):
        data = super().get_context_data(**kwargs)
        data['projects'] = Project.objects.active()[:3]
        data['user_projects_inprogress'] = UserProject.objects.filter(
            status__in=(UserProject.STATUS_IN_PROGRESS,
                        UserProject.STATUS_PENDING_REVIEW,
                        UserProject.STATUS_INCOMPLETE)
        ).order_by('-updated')[:5]
        data['user_projects_completed'] = UserProject.objects.filter(
            status=UserProject.STATUS_COMPLETE
        ).order_by('-updated')[:5]
        return data

upkoding/base/templates/base/_field.html
{% load base %}
<div class="{{ classes }}">
    <label for="{{ field.name }}" class="form-label">{{ field.label }}</label>
    {{ field|input_class:'form-control' }}
    {% if field.help_text %}
    <div class="form-text">{{ field.help_text }}</div>
    {% endif %}
    <div class="invalid-feedback">
        {{ field.errors }}
    </div>
</div>

upkoding/base/templates/base/_inprogress.html
{% load static %}
<div class="text-center">
    <img src="{% static 'base/img/in_progress.svg' %}" height="300">
    <p class="lead mt-2">In progress...</p>
</div>

upkoding/base/templates/base/_messages.html
{% if messages %}
{% for message in messages %}
<div class="alert {%if closable %}alert-dismissible fade show{% endif %} alert-{% if message.tags %}{{ message.tags }}{% endif %}"
    role="alert">
    {{ message }}
    {% if closable %}
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
    {% endif %}
</div>
{% endfor %}
{% endif %}

upkoding/base/templates/base/_pagination.html
<nav aria-label="Paginasi" class="mt-5">
    <ul class="pagination justify-content-center">
        {% if page_obj.has_previous %}
        <li class="page-item"><a class="page-link"
                href="?page=1{% if search_query %}&s={{ search_query }}{% endif %}">Pertama</a></li>
        <li class="page-item">
            <a class="page-link"
                href="?page={{ page_obj.previous_page_number }}{% if search_query %}&s={{ search_query }}{% endif %}">
                <i class="bi bi-arrow-left"></i>
            </a>
        </li>
        {% endif %}
        <li class="page-item disabled">
            <a class="page-link" href="#" tabindex="-1" aria-disabled="true">{{ page_obj.number }}</a>
        </li>
        {% if page_obj.has_next %}
        <li class="page-item">
            <a class="page-link"
                href="?page={{ page_obj.next_page_number }}{% if search_query %}&s={{ search_query }}{% endif %}">
                <i class="bi bi-arrow-right"></i>
            </a>
        </li>
        <li class="page-item"><a class="page-link"
                href="?page={{ page_obj.paginator.num_pages }}{% if search_query %}&s={{ search_query }}{% endif %}">
                Terakhir
            </a>
        </li>
        {% endif %}
    </ul>
</nav>

upkoding/base/templates/base/base.html
<!doctype html>
<html lang="en" class="h-100">
{% load static %}
{% load base %}

<head>
    {% block meta %}{% meta %}{% endblock %}
    <!-- Bootstrap core CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/css/bootstrap.min.css" rel="stylesheet"
        integrity="sha384-giJF6kkoqNQ00vy+HMDP7azOuL0xtbfIcaT9wjKHr8RbDVddVHyTfAAsrekwKmP1" crossorigin="anonymous">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.3.0/font/bootstrap-icons.css">

    <!-- Favicons -->
    <link rel="apple-touch-icon" sizes="180x180" href="{% static 'base/img/favicon/apple-touch-icon.png' %}">
    <link rel="icon" type="image/png" sizes="32x32" href="{% static 'base/img/favicon/favicon-32x32.png' %}">
    <link rel="icon" type="image/png" sizes="16x16" href="{% static 'base/img/favicon/favicon-16x16.png' %}">
    <link rel="manifest" href="{% static 'base/img/favicon/site.webmanifest' %}">
    <link rel="mask-icon" href="{% static 'base/img/favicon/safari-pinned-tab.svg' %}" color="#5bbad5">
    <meta name="msapplication-TileColor" content="#da532c">
    <meta name="theme-color" content="#ffffff">

    <!-- Custom styles for this template -->
    <link href="{% static 'base/css/global.css' %}" rel="stylesheet">
    {% block headscripts %}{% endblock %}

    {% if ga_tracking_id %}
    <!-- Global site tag (gtag.js) - Google Analytics -->
    <script async src="https://www.googletagmanager.com/gtag/js?id={{ ga_tracking_id }}"></script>
    <script>
        window.dataLayer = window.dataLayer || [];
        function gtag() { dataLayer.push(arguments); }
        gtag('js', new Date());
        gtag('config', '{{ ga_tracking_id }}');
    </script>
    {% endif %}
</head>

<body class="d-flex h-100">
    <div class="custom-container w-100 h-100 p-3 mx-auto flex-column d-flex">
        <header class="{% block header_mb %}mb-auto{% endblock%}">
            <div>
                <a href="{% url 'base:index' %}" class="logo">
                    <h3 class="float-md-start mb-0" style="position: relative;">upkoding
                        <span class="badge bg-primary"
                            style="font-size: 12px; position: absolute; top: 10px; right: -50px">BETA</span>
                    </h3>
                </a>
                <nav class="nav nav-masthead justify-content-center float-md-end">
                    <a class="nav-link {% active_class '/proyek/*' %}" href="{% url 'projects:list' %}">Proyek</a>
                    <a class="nav-link {% active_class '/coders/*' %}" href="{% url 'coders:list' %}">Coders</a>
                    <a class="nav-link {% active_class 'base:forum' %}" href="{% url 'base:forum' %}">Diskusi</a>
                    <a class="nav-link {% active_class 'base:tentang' %}" href="{% url 'base:tentang' %}">Tentang</a>
                    {% if user.is_authenticated %}
                    <div class="btn-group ms-4" style="margin-top: -1px">
                        <a href="{% url 'account:settings' %}" class="btn btn-outline-default nav-link">
                            {{ user|avatar_img:25 }} <span class="ms-1">{{ user.username }}</span>
                        </a>
                        <button type="button" class="btn btn-outline-default dropdown-toggle dropdown-toggle-split"
                            data-bs-toggle="dropdown" aria-expanded="false">
                            <span class="visually-hidden">Toggle Dropdown</span>
                        </button>
                        <ul class="dropdown-menu">
                            <li><a class="dropdown-item" href="{% url 'account:logout' %}">Logout</a></li>
                        </ul>
                    </div>
                    {% else %}
                    <a class="nav-link ms-4" href="{% url 'account:login' %}"><i class="bi bi-person-circle me-1"></i>
                        Login</a>
                    {% endif %}
                </nav>
            </div>
        </header>

        <main>
            {% block content %}{% endblock %}
            <div class="card text-dark bg-light mb-5 mt-5">
                <div class="card-body">
                    <h5 class="card-title">Under Development!</h5>
                    <p class="card-text">Terima kasih sudah berkunjung ke UpKoding, namun saat ini platform ini belum
                        dibuka untuk umum. Baru online untuk mengetes fitur, mengisi data proyek serta menguji
                        workflow CI/CD nya.</p>
                    <p class="card-text">Silahkan buat akun, lihat-lihat proyeknya atau mulai mengerjakan. <a
                            href="https://github.com/upkoding/upkoding/discussions" target="_blank"
                            rel="noreferrer noopener">Any feedback are welcome!</a></p>
                    <p class="card-text">Happy Coding!</p>
                </div>
            </div>
        </main>

        <footer class="mt-auto text-center" style="padding-top: 50px;">
            <nav class="nav nav-masthead justify-content-center">
                <a class="nav-link" href="{% url 'projects:list' %}">Proyek</a>
                <a class="nav-link" href="{% url 'coders:list' %}">Coders</a>
                <a class="nav-link" href="{% url 'base:forum' %}">Diskusi</a>
                <a class="nav-link" href="{% url 'base:tentang' %}">Tentang</a>
            </nav>

            <p style="color: grey; margin-top: 1em;">Powered by <a href="https://github.com/upkoding/upkoding"
                    target="_blank">upkoding</a>
                {% if user.is_authenticated and user.is_staff %}
                | <a href="{% url 'admin:index' %}">admin</a>
                {% endif %}
            </p>
        </footer>
    </div>
    <script>window.csrftoken = '{{ csrf_token }}'</script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-ygbV9kiqUc6oa4msXn9868pTtWMgiQaeYH7/t7LECLbyPA2x65Kgf80OJFdroafW"
        crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/gh/alpinejs/alpine@v2.8.0/dist/alpine.min.js" defer></script>
    {% block footscripts %}{% endblock %}
</body>

</html>

upkoding/base/templates/base/forum.html
{% extends 'base/base.html' %}

{% block title %}Forum Diskusi Pemrograman{% endblock %}

{% block content %}
{% include 'base/_inprogress.html' %}
{% endblock %}

upkoding/base/templates/base/index.html
{% extends 'base/base.html' %}
{% load base %}
{% load sorl_thumbnail %}
{% load humanize %}

{% block header_mb %}mb-5{% endblock %}

{% block content %}
<div class="row justify-content-md-center mt-5">
    <div class="col col-lg-10">
        <div class="text-center" style="padding: 0 3em">
            <h1>Belajar coding menyenangkan!</h1>
            <p class="lead" style="margin-top: 1rem; margin-bottom: 2rem;">Cara belajar pemrograman yang paling efektif
                adalah
                dengan <strong>membuat proyek</strong>.
                Tantang diri kamu untuk mengerjakan ide-ide proyek yang sudah disediakan dan dapatkan poin untuk setiap
                proyek
                yang terselesaikan.
            </p>
            <p class="lead">
                <a href="{% url 'projects:list' %}" class="btn btn-lg btn-primary">Lihat semua proyek <i
                        class="bi bi-arrow-right"></i></a>
            </p>
        </div>
    </div>
</div>
<div class="content row row-cols-sm-1 row-cols-md-2 row-cols-lg-3 g-5 mt-5 mb-5">
    {% if projects %}
    {% for project in projects %}
    {% include 'projects/_project_list_item.html' with project=project %}
    {% endfor %}
    {% endif %}
</div>
<div style="height: 20px;" class="border-top"></div>
<div class="row mt-5 mb-5 content">
    <div class="col col-lg-6 left">
        <h5 class="section-title mb-5"><i class="bi bi-code-slash me-2"></i>Lagi Dikerjakan</h5>
        {% for item in user_projects_inprogress %}
        {% with u=item.user p=item.project %}
        <div class="position-relative mb-4 clearfix">
            {% thumbnail p.cover "160x160" crop="center" as im %}
            <img src="{{ im.url }}" width="80" height="80" class="me-3 rounded float-start" alt="{{ p.title|title }}">
            {% endthumbnail %}
            <div>
                <h6 class="mt-0 mb-1">{{ p.title|title }}</h6>
                <small class="text-muted">
                    <img src="{{ u|avatar_url:40 }}" height="20" width="20" class="rounded-circle me-1" alt="avatar" />
                    <strong>{{ u.username }}</strong> mengerjakan
                    {{ item.updated|naturaltime }}
                </small>
                <a href="{{ item.get_absolute_url }}" class="stretched-link"></a>
                <div class="progress mt-2" style="height: 3px;">
                    <div class="progress-bar progress-bar-striped bg-{{ item.get_color_class }}" role="progressbar"
                        style="width: {{ item.requirements_completed_percent|safe }}%"
                        aria-valuenow="{{ item.requirements_completed_percent|safe }}" aria-valuemin="0"
                        aria-valuemax="100">
                    </div>
                </div>
            </div>
        </div>
        {% endwith %}
        {% endfor %}
    </div>

    <div class="col col-lg-6 right">
        <h5 class="section-title mb-5"><i class="bi bi-check2-circle me-2"></i> Berhasil Diselesaikan</h5>
        {% for item in user_projects_completed %}
        {% with u=item.user p=item.project %}
        <div class="position-relative mb-4 clearfix">
            {% thumbnail p.cover "160x160" crop="center" as im %}
            <img src="{{ im.url }}" width="80" height="80" class="me-3 rounded float-start" alt="{{ p.title|title }}">
            {% endthumbnail %}
            <div>
                <h6 class="mt-0 mb-1">{{ p.title|title }}</h6>
                <small class="text-muted">
                    <img src="{{ u|avatar_url:40 }}" height="20" width="20" class="rounded-circle me-1" alt="avatar" />
                    <strong>{{ u.username }}</strong> menyelesaikan
                    {{ item.updated|naturaltime }}
                </small>
                <a href="{{ item.get_absolute_url }}" class="stretched-link"></a>
                <div class="progress mt-2" style="height: 3px;">
                    <div class="progress-bar progress-bar-striped bg-{{ item.get_color_class }}" role="progressbar"
                        style="width: {{ item.requirements_completed_percent|safe }}%"
                        aria-valuenow="{{ item.requirements_completed_percent|safe }}" aria-valuemin="0"
                        aria-valuemax="100">
                    </div>
                </div>
            </div>
        </div>
        {% endwith %}
        {% endfor %}
    </div>
</div>

{% endblock %}

upkoding/base/templates/base/tentang.html
{% extends 'base/base.html' %}
{% block title %}Tentang UpKoding{% endblock %}

{% block content %}
{% include 'base/_inprogress.html' %}
{% endblock %}