upkoding/base/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic.base import TemplateView

from .views import render_template, Index

app_name = 'base'


urlpatterns = [
    path('', Index.as_view(), name='index'),
    path('diskusi/', render_template('base/forum.html'), name='forum'),
    path('tentang/', render_template('base/tentang.html'), name='tentang'),
    path('robots.txt', render_template('base/robots.txt', 'text/plain')),
]

upkoding/projects/urls.py
from django.urls import path

from .views import project, review

app_name = 'projects'

urlpatterns = [
    path('<slug:slug>-<int:pk>/<str:username>/',
         project.ProjectDetailUser.as_view(), name='detail_user'),
    path('<slug:slug>-<int:pk>/', project.ProjectDetail.as_view(), name='detail'),
    path('<int:pk>/review', review.ProjectReview.as_view(), name='review'),
    path('', project.ProjectList.as_view(), name='list'),
]

upkoding/upkoding/urls.py
from django.conf import settings
from django.contrib import admin
from django.http.response import HttpResponse
from django.urls import path, include
from django.contrib.staticfiles.urls import static


def appengine_warmup(request):
    return HttpResponse('ok')


urlpatterns = [
    path('admin/', admin.site.urls),
    path('account/', include('account.urls', namespace='account')),
    path('proyek/', include('projects.urls', namespace='projects')),
    path('coders/', include('coders.urls', namespace='coders')),
    path('_ah/warmup/', appengine_warmup),
    path('', include('base.urls', namespace='base')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

upkoding/projects/models.py
from django.db import models
from django.db.models import Q
from django.db.models.deletion import CASCADE
from django.template.defaultfilters import slugify
from django.urls import reverse
from django.conf import settings
from django.utils.timezone import now
from django.contrib.postgres.indexes import GinIndex
from django.contrib.postgres.search import (
    SearchQuery,
    SearchRank,
    SearchVector,
    SearchVectorField,
    TrigramSimilarity
)

from sorl.thumbnail import ImageField
from account.models import User

PROJECT_SEARCH_VECTORS = (SearchVector('title', weight='A') +
                          SearchVector('tags', weight='A') +
                          SearchVector('description_short', weight='B') +
                          SearchVector('description', weight='C'))


def project_cover_path(instance, filename):
    """
    Custom cover path: projects/cover/123455678-hello-world.png
    """
    ts = int(now().timestamp())
    return 'projects/cover/{}-{}'.format(ts, filename)


def project_image_path(instance, filename):
    """
    Custom cover path: projects/images/12345678-hello-world.png
    """
    ts = int(now().timestamp())
    return 'projects/images/{}-{}'.format(ts, filename)


class ProjectManager(models.Manager):
    """
    Custom manager for `Project` with some helper methods to work with Project.
    """

    def active(self):
        """
        Returns active projects only.
        Usage:
            `Project.objects.active()`
        Which is equivalent to:
            `Project.objects.all(status=2)`
        """
        return self.filter(status=2)

    def featured(self):
        """
        Returns featured projects only.
        Usage:
            `Project.objects.featured()`
        Which is equivalent to:
            `Project.objects.all(status=2, is_featured=True)`
        """
        return self.filter(status=2, is_featured=True)

    def search(self, text):
        """
        Provides an easy way to do Full Text Search.
        Usage:
            `Project.objects.search('django')`
        """
        search_query = SearchQuery(text)
        search_rank = SearchRank(PROJECT_SEARCH_VECTORS, search_query)
        trigram_similarity = TrigramSimilarity('title', text) + \
            TrigramSimilarity('tags', text) + \
            TrigramSimilarity('description_short', text)
        return self.get_queryset() \
            .annotate(rank=search_rank, similarity=trigram_similarity) \
            .filter(status=2) \
            .filter(Q(rank__gte=0.2) | Q(similarity__gt=0.1)) \
            .order_by('-rank')


class Project(models.Model):
    """
    Project that can be picked-up by users.
    """
    # statuses
    STATUS_DRAFT = 0
    STATUS_PENDING = 1
    STATUS_ACTIVE = 2
    STATUS_DELETED = 3
    STATUSES = [
        (STATUS_DRAFT, 'Draft'),
        (STATUS_PENDING, 'Pending'),
        (STATUS_ACTIVE, 'Active'),
        (STATUS_DELETED, 'Deleted'),
    ]

    user = models.ForeignKey(
        User,
        on_delete=models.SET_NULL,
        null=True,
        related_name='projects')
    slug = models.SlugField(max_length=150, blank=True)
    title = models.CharField('Judul', max_length=100)
    description_short = models.CharField(
        'Deskripsi Pendek', max_length=100, default='')
    description = models.TextField('Deskripsi')
    requirements = models.JSONField('Requirements', blank=True, null=True)
    cover = ImageField(
        upload_to=project_cover_path,
        blank=True,
        null=True
    )
    point = models.IntegerField(default=0)
    tags = models.CharField('Tags', max_length=50, blank=True, default='')
    is_featured = models.BooleanField(default=False)
    status = models.PositiveSmallIntegerField(
        'Status', choices=STATUSES, default=STATUS_DRAFT)

    # whether user need to provide `demo_url` and/or `sourcecode_url` before project
    # marked as complete.
    require_demo_url = models.BooleanField(default=False)
    require_sourcecode_url = models.BooleanField(default=False)

    taken_count = models.IntegerField(default=0)
    completed_count = models.IntegerField(default=0)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)

    # full text search
    search_vector = SearchVectorField(null=True, blank=True)

    # custom manager
    objects = ProjectManager()

    class Meta:
        indexes = [
            models.Index(fields=['slug'], name='project_slug_idx'),
            models.Index(fields=['status'], name='project_status_idx'),
            GinIndex(fields=['search_vector'],
                     name='project_search_vector_idx'),
        ]
        ordering = ['-created']

    def __str__(self, *args, **kwargs):
        return self.title

    def save(self, *args, **kwargs):
        # set slug
        if not self.slug:
            self.slug = slugify(self.title)

        # cleanup tags
        if self.tags:
            self.tags = ','.join([
                tag.strip().lower()
                for tag in self.tags.split(',')])

        # set search_vector on update
        # TODO: update this asynchronously (using PubSub / Cloud Task)
        if self.pk:
            self.search_vector = PROJECT_SEARCH_VECTORS
        super().save(*args, **kwargs)

    def is_active(self):
        return self.status == self.STATUS_ACTIVE

    def get_absolute_url(self):
        return reverse('projects:detail', args=[self.slug, str(self.pk)])

    def get_point_display(self):
        return '{}{}'.format(self.point, settings.POINT_UNIT)

    def inc_taken_count(self):
        self.taken_count = models.F('taken_count') + 1
        self.save()

    def inc_completed_count(self):
        self.completed_count = models.F('completed_count') + 1
        self.save()

    def dec_completed_count(self):
        self.completed_count = models.F('completed_count') - 1
        self.save()

    def assign_to(self, user):
        """
        Returns `UserProject` instance and created (bool).
        - If user already pick this project, return that one instead of creating new one
          since user can only work on the same project once.
        - If user never pick this project, create new `UserProject`.
        - Add project creator to the UserProjectParticipant so we can notify them for event in this project.
        - Last, we increment the taken count.
        """
        obj, created = UserProject.objects.get_or_create(
            user=user,
            project=self,
            defaults={
                'requirements': self.requirements,
                'point': self.point,
                'require_demo_url': self.require_demo_url,
                'require_sourcecode_url': self.require_sourcecode_url,
            })
        if created:
            # add project creator as participant
            UserProjectParticipant.objects.get_or_create(
                user_project=obj, user=self.user
            )
            # add user who working on the project as participant
            UserProjectParticipant.objects.get_or_create(
                user_project=obj, user=user)
            # inc taken count
            self.inc_taken_count()
        return (obj, created)


class ProjectImage(models.Model):
    project = models.ForeignKey(
        Project, on_delete=models.CASCADE, related_name='images')
    title = models.CharField(max_length=250, blank=True, default='')
    order = models.SmallIntegerField(default=0)
    image = ImageField(
        upload_to=project_image_path,
    )
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)


class UserProject(models.Model):
    """
    Status of project that picked-up by user.
    The original project data itself may changed overtime, but UserProject will holds
    the snapshot of important data (requirements, point) at the time user pick this project.
    """
    # statuses
    STATUS_IN_PROGRESS = 0
    STATUS_PENDING_REVIEW = 1
    STATUS_COMPLETE = 2
    STATUS_INCOMPLETE = 3
    STATUSES = [
        (STATUS_IN_PROGRESS, 'In Progress'),
        (STATUS_PENDING_REVIEW, 'Pending Review'),
        (STATUS_COMPLETE, 'Complete'),
        (STATUS_INCOMPLETE, 'Incomplete'),
    ]

    user = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        related_name='user_projects')
    project = models.ForeignKey(
        Project,
        on_delete=models.CASCADE,
        related_name='user_projects')
    requirements = models.JSONField('Requirements', blank=True, null=True)
    requirements_completed_percent = models.DecimalField(
        default=0.0, decimal_places=2, max_digits=5)  # max value: 100.00
    requirements_completed_percent_max = models.DecimalField(
        default=0.0, decimal_places=2, max_digits=5)
    point = models.IntegerField(default=0)
    status = models.PositiveSmallIntegerField(
        'Status', choices=STATUSES, default=STATUS_IN_PROGRESS)

    # information bellow can be added by user when confirming the project completion
    demo_url = models.CharField(
        'URL demo proyek', max_length=250, blank=True, default='')
    sourcecode_url = models.CharField(
        'URL kode sumber proyek', max_length=250, blank=True, default='')
    note = models.TextField('Catatan', blank=True, default='')

    # whether user need to provide `demo_url` and/or `sourcecode_url` before project
    # marked as complete.
    require_demo_url = models.BooleanField(default=False)
    require_sourcecode_url = models.BooleanField(default=False)

    likes_count = models.IntegerField(default=0)
    comments_count = models.IntegerField(default=0)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)

    class Meta:
        indexes = [
            # to make sure get UserProject by `user` and `project` query fast
            models.Index(fields=['user', 'project'], name='user_project_idx'),

upkoding/projects/forms.py
from django import forms
from django.core.exceptions import ValidationError

from .models import UserProject


class UserProjectReviewRequestForm(forms.ModelForm):
    kind = forms.CharField(widget=forms.HiddenInput(),
                           initial='review_request')

    class Meta:
        model = UserProject
        fields = ['demo_url', 'sourcecode_url', 'note']

    def clean_demo_url(self):
        url = self.cleaned_data['demo_url']
        if self.instance.require_demo_url and not url:
            raise ValidationError('URL Proyek harus diisi')
        return url

    def clean_sourcecode_url(self):
        url = self.cleaned_data['sourcecode_url']
        if self.instance.require_sourcecode_url and not url:
            raise ValidationError('URL kode sumber proyek harus diisi')
        return url

    def submit_review(self):
        """
        A shortcut to set `status` to Pending Review and save the project.
        Returns Boolean whether status changed or not
        """
        if self.instance.status >= UserProject.STATUS_PENDING_REVIEW:
            self.save()
            return False

        user_project = self.save(commit=False)
        user_project.status = UserProject.STATUS_PENDING_REVIEW
        user_project.save()
        return True

upkoding/projects/views/review.py
import json
from django.http.response import HttpResponseForbidden, JsonResponse
from django.contrib.auth.mixins import LoginRequiredMixin
from django.views.generic import DetailView
from django.db import transaction

from projects.models import UserProject, UserProjectEvent


class ProjectReview(LoginRequiredMixin, DetailView):
    model = UserProject

    def post(self, request, *args, **kwargs):
        user_project = self.get_object()

        # payload
        data = json.loads(request.body)
        message = data.get('message', '')
        action = data.get('action', '')

        owner = user_project.user
        current_user = request.user

        # only owner and staff can write message to project timeline
        if action == 'message' and ((current_user == owner) or current_user.is_staff):
            user_project.add_event(
                UserProjectEvent.TYPE_REVIEW_MESSAGE,
                user=current_user,
                message=message)
            return JsonResponse({'ok': True})

        # staff can approve projects, but staff project need to be approved by admin :)
        if action == 'approve' and user_project.approvable_by(current_user):
            with transaction.atomic():
                user_project.status = UserProject.STATUS_COMPLETE
                user_project.save()

                # add point to user
                owner.add_point(user_project.point)

                # increment completed count on project
                project = user_project.project
                project.inc_completed_count()

                user_project.add_event(
                    UserProjectEvent.TYPE_PROJECT_COMPLETE,
                    user=current_user,
                    message=message)
                return JsonResponse({'ok': True})

        # only superuser can disapprove (drop the status back to pending review) approved project
        if action == 'disapprove' and current_user.is_superuser:
            was_complete = user_project.is_complete()

            with transaction.atomic():
                user_project.status = UserProject.STATUS_PENDING_REVIEW
                user_project.save()

                # withdraw point and counter if it was approved
                if was_complete:
                    owner.remove_point(user_project.point)

                    # decrement completed count on project
                    project = user_project.project
                    project.dec_completed_count()

                user_project.add_event(
                    UserProjectEvent.TYPE_PROJECT_INCOMPLETE,
                    user=current_user,
                    message=message)
                return JsonResponse({'ok': True})

        return HttpResponseForbidden()

upkoding/projects/templates/projects/templatetags/completed_projects.html
{% load base %}
<div class="user-progress">
    {% if items %}
    {% for item in items %}
    <a href="{{ item.get_absolute_url }}">
        <div class="card">
            <div class="card-body">
                <h6 class="card-title">
                    {% with u=item.user %}
                    <img src="{{ u|avatar_url:40 }}" height="20" width="20" class="rounded-circle" alt="avatar" />
                    {{ u.username }}
                    <small>
                        (+{{ item.get_point_display }})
                    </small>
                    {% endwith %}
                </h6>
                <div class="progress" style="height: 3px; margin-left: 36px;">
                    <div class="progress-bar progress-bar-striped bg-{{ item.get_color_class }}" role="progressbar"
                        style="width: {{ item.requirements_completed_percent|safe }}%"
                        aria-valuenow="{{ item.requirements_completed_percent|safe }}" aria-valuemin="0"
                        aria-valuemax="100"></div>
                </div>
            </div>
        </div>
    </a>
    {% endfor %}
    {% else %}
    <div class="card text-center">
        <div class="card-body">
            <p class="card-text" style="color: grey;">Belum ada yang menyelesaikan.</p>
        </div>
    </div>
    {% endif %}
</div>

upkoding/projects/templates/projects/templatetags/inprogress_projects.html
{% load base %}
<div class="user-progress">
    {% if items %}
    {% for item in items %}
    <a href="{{ item.get_absolute_url }}">
        <div class="card">
            <div class="card-body">
                <h6 class="card-title">
                    {% with u=item.user %}
                    <img src="{{ u|avatar_url:40 }}" height="20" width="20" class="rounded-circle" alt="avatar" />
                    {{ u.username }}
                    <small>
                        ({{ item.requirements_completed_percent|floatformat:1 }}%)
                    </small>
                    {% endwith %}
                </h6>
                <div class="progress" style="height: 3px; margin-left: 36px;">
                    <div class="progress-bar progress-bar-striped bg-{{ item.get_color_class }}" role="progressbar"
                        style="width: {{ item.requirements_completed_percent|safe }}%"
                        aria-valuenow="{{ item.requirements_completed_percent|safe }}" aria-valuemin="0"
                        aria-valuemax="100"></div>
                </div>
            </div>
        </div>
    </a>
    {% endfor %}
    {% else %}
    <div class="card text-center">
        <div class="card-body">
            <p class="card-text" style="color: grey;">Belum ada yang mengerjakan.</p>
        </div>
    </div>
    {% endif %}
</div>

upkoding/projects/templates/projects/templatetags/render_requirements.html
{% if requirements %}
<div class="list-group requirements">
    {% for req in requirements %}
    <div class="list-group-item list-group-item-action" aria-current="true">
        <div class="d-flex w-100 justify-content-between">
            <h6 class="mb-1"><i class="bi bi-stop me-2"></i>{{ req.title }}</h6>
        </div>
        {% if req.desc %}
        <div class="ms-4"><small class="help">{{ req.desc }}</small></div>
        {% endif %}
    </div>
    {% endfor %}
</div>
{% endif %}

upkoding/projects/templates/projects/templatetags/render_requirements_form.html
{% if requirements %}
<div class="progress">
    <div class="progress-bar progress-bar-striped bg-{{ user_project.get_color_class }}" role="progressbar"
        style="width: {{ user_project.requirements_completed_percent|safe }}%" aria-valuenow="10" aria-valuemin="0"
        aria-valuemax="100">
        {% if user_project.requirements_completed_percent > 0.0 %}
        {{ user_project.requirements_completed_percent|floatformat:1 }}%
        {% endif %}
    </div>
</div>

<div class="list-group requirements mt-3">
    {% if editable %}<form method="POST">{% endif %}
        {% csrf_token %}
        <input type="hidden" name="kind" value="update" />
        {% for req in requirements %}
        <label for="reqs-{{ forloop.counter0 }}"
            class="list-group-item list-group-item-action {% if req.complete %}list-group-item-{{ user_project.get_color_class }}{% endif %}"
            style="cursor: pointer;">
            <div class="d-flex w-100 justify-content-between">
                <h6 class="mb-1">
                    <input {% if req.complete %}checked{% endif %} {% if not editable %}disabled{% endif %}
                        class="form-check-input me-2" type="checkbox" name="reqs" id="reqs-{{ forloop.counter0 }}"
                        value="{{ forloop.counter0 }}">
                    {{ req.title }}
                </h6>
            </div>
            {% if req.desc %}
            <div class="ms-4"><small class="help">{{ req.desc }}</small></div>
            {% endif %}
        </label>
        {% endfor %}

        {% if editable %}
        <!-- is_owner && editable -->
        <div class="row mt-3">
            <div class="col col-6">
                <button type="submit" class="btn btn-outline-{{ user_project.get_color_class }}">Update
                    Progress</button>
            </div>
            <div class="col col-6" style="text-align: right;">
                {% if user_project.is_requirements_complete %}
                <a href="?form=1" class="btn btn-success" title="Minta proyek untuk direview">
                    Minta Review <i class="bi bi-arrow-right"></i>
                </a>
                {% else %}
                <button type="button" class="btn btn-outline-danger" data-bs-toggle="modal"
                    data-bs-target="#deleteUserProjectModal">Batalkan Proyek
                </button>
                {% endif %}
            </div>
        </div>
        {% elif is_owner %}
        <!-- !editable && is_owner: owner can edit the completion detail -->
        <div class="row mt-3">
            <div class="col col-12">
                <a href="?form=1" class="btn btn-outline-success float-end" title="Edit detail">
                    Edit detail <i class="bi bi-arrow-right"></i>
                </a>
            </div>
        </div>
        {% endif %}
    </form>
</div>

<!-- Modal -->
{% if editable %}
<div class="modal fade" id="deleteUserProjectModal" tabindex="-1" aria-labelledby="deleteUserProjectModalLabel"
    aria-hidden="true">
    <div class="modal-dialog modal-dialog-centered" x-data="deleteForm()">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="deleteUserProjectModalLabel">Batalkan proyek?</h5>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
            <div class="modal-body">
                Kamu yakin ga jadi mengerjakan proyek ini? Kalau menemui kesulitan atau ada yang kurang jelas kamu bisa
                bertanya ke teman lainnya (<a href="" target="_blank">disini</a>).

                <div class="alert alert-danger mt-4" role="alert" x-show="error !== null" x-text="error"></div>
            </div>
            <div class="modal-footer">
                <form method="POST" @submit.prevent="deleteProject">
                    {% csrf_token %}
                    <input type="hidden" name="kind" value="delete" />
                    <button type="submit" class="btn btn-primary"
                        x-text="loading ? 'Membatalkan...' : 'Batalkan'"></button>
                </form>
            </div>
        </div>
    </div>
</div>
<script type="text/javascript">
    window.deleteForm = function () {
        return {
            loading: false,
            error: null,
            deleteProject(e) {
                this.loading = true
                // make ajax call
                fetch('', {
                    method: 'POST',
                    body: new FormData(e.target)
                }).then((resp) => {
                    if (resp.ok) {
                        window.location.href = '{{ user_project.get_project_url }}'
                    } else {
                        this.error = resp.statusText
                    }
                }).finally(() => {
                    this.loading = false
                })
            }
        }
    }
</script>
{% endif %}

{% endif %}

upkoding/projects/templates/projects/templatetags/render_review_request_form.html
{% if editable %}
<div x-data="completionForm()">
    <form method="POST" @submit.prevent="submit">
        {% csrf_token %}
        {% for field in form.hidden_fields %}
        {{ field }}
        {% endfor %}

        {% if user_project.require_demo_url %}
        <div class="mb-4">
            <label for="demo_url" class="form-label">
                <strong><i class="bi bi-link-45deg"></i>
                    URL Proyek</strong>
            </label>
            <input type="text" name="demo_url" maxlength="250" class="form-control"
                :class="{ 'is-invalid': errors.demo_url }" id="id_demo_url" value="{{ form.demo_url.value }}">
            <div class="form-text">URL proyek live atau demo. contoh: https://codepen.io/aexcode/pen/vYyQxoK</div>
            <div class="invalid-feedback" x-text="errors.demo_url && errors.demo_url[0].message"></div>
        </div>
        {% endif %}

        {% if user_project.require_sourcecode_url %}
        <div class="mb-4">
            <label for="sourcecode_url" class="form-label"><strong><i class="bi bi-link-45deg"></i> URL kode sumber
                    proyek</strong></label>
            <input type="text" name="sourcecode_url" maxlength="250" class="form-control"
                :class="{ 'is-invalid': errors.sourcecode_url }" id="id_sourcecode_url"
                value="{{ form.sourcecode_url.value }}">
            <div class="form-text">Bisa di Github, GitLab atau Bitbucket. contoh: https://github.com/upkoding/upkoding
            </div>
            <div class="invalid-feedback" x-text="errors.sourcecode_url && errors.sourcecode_url[0].message"></div>
        </div>
        {% endif %}

        <div class="mb-4">
            <label for="note" class="form-label"><i class="bi bi-chat-left-text"></i> Catatan (optional)</label>
            <textarea name="note" cols="40" rows="10" class="form-control" id="id_note">{{ form.note.value }}</textarea>
            <div class="form-text">Catatan untuk reviewer atau kesan dan pesan selama mengerjakan proyek ini, apa yang dipelajari dll.</div>
        </div>

        <div class="row mt-3">
            <div class="col col-6">
                <a href="{{ user_project.get_absolute_url }}" class="btn btn-outline-secondary" title="Kembali">
                    <i class="bi bi-arrow-left"></i> Kembali
                </a>
            </div>
            <div class="col col-6">
                {% if user_project.is_in_progress %}
                <button type="submit" class="btn btn-success float-end"
                    x-text="loading ? 'Mengirim Request...': 'Kirim Request'"></button>
                {% else %}
                <button type="submit" class="btn btn-success float-end"
                    x-text="loading ? 'Mengupdate...': 'Update detail'"></button>
                {% endif %}
            </div>
        </div>
    </form>
</div>
<script type="text/javascript">
    window.completionForm = function () {
        return {
            loading: false,
            errors: {},
            submit(e) {
                this.loading = true
                // make ajax call
                fetch('', {
                    method: 'POST',
                    body: new FormData(e.target)
                }).then(async (resp) => {
                    if (resp.ok) {
                        window.location.href = '{{ user_project.get_absolute_url }}'
                    } else {
                        this.errors = await resp.json()
                    }
                }).finally(() => {
                    this.loading = false
                })
            }
        }
    } 
</script>
{% endif %}

upkoding/projects/templates/projects/templatetags/render_tags.html
{% if tags %}
<div class="tags">
    {% for tag in tags %}
    <a href="{% url 'projects:list' %}?s={{ tag }}">
        <span class="badge bg-{{ color }}">{{ tag }}</span>
    </a>
    {% endfor %}
</div>
{% endif %}

upkoding/projects/templates/projects/templatetags/render_timeline.html
<ul class="timeline mt-4">
    {% for event in events %}
    <li>
        {% with event_user=event.obj.user %}
        {% include 'projects/templatetags/timeline/avatar.html' with u=event_user %}
        {% include event.tpl with object=event.obj %}
        {% endwith %}
    </li>
    {% endfor %}

    {% if user == user_project.user and not user_project.is_in_progress %}
    <!-- if project owner, show review form (message mode only) -->
    <li>
        {% include 'projects/templatetags/timeline/avatar.html' with u=user %}
        {% include 'projects/templatetags/timeline/review_form.html' with fullmode=False %}
    </li>
    {% endif %}

    {% if user.is_staff and user != user_project.user %}
    <!-- if current user is staff and project waiting for review, show review form (full mode) -->
    <li>
        {% include 'projects/templatetags/timeline/avatar.html' with u=user %}
        {% include 'projects/templatetags/timeline/review_form.html' with fullmode=True %}
    </li>
    {% endif %}
</ul>