upkoding/base/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic.base import TemplateView

from .views import render_template, Index

app_name = 'base'


urlpatterns = [
    path('', Index.as_view(), name='index'),
    path('diskusi/', render_template('base/forum.html'), name='forum'),
    path('tentang/', render_template('base/tentang.html'), name='tentang'),
    path('robots.txt', render_template('base/robots.txt', 'text/plain')),
]

upkoding/projects/urls.py
from django.urls import path

from .views import project, review

app_name = 'projects'

urlpatterns = [
    path('<slug:slug>-<int:pk>/<str:username>/',
         project.ProjectDetailUser.as_view(), name='detail_user'),
    path('<slug:slug>-<int:pk>/', project.ProjectDetail.as_view(), name='detail'),
    path('<int:pk>/review', review.ProjectReview.as_view(), name='review'),
    path('', project.ProjectList.as_view(), name='list'),
]

upkoding/upkoding/urls.py
from django.conf import settings
from django.contrib import admin
from django.http.response import HttpResponse
from django.urls import path, include
from django.contrib.staticfiles.urls import static


def appengine_warmup(request):
    return HttpResponse('ok')


urlpatterns = [
    path('admin/', admin.site.urls),
    path('account/', include('account.urls', namespace='account')),
    path('proyek/', include('projects.urls', namespace='projects')),
    path('coders/', include('coders.urls', namespace='coders')),
    path('_ah/warmup/', appengine_warmup),
    path('', include('base.urls', namespace='base')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

upkoding/projects/forms.py
from django import forms
from django.core.exceptions import ValidationError

from .models import UserProject


class UserProjectReviewRequestForm(forms.ModelForm):
    kind = forms.CharField(widget=forms.HiddenInput(),
                           initial='review_request')

    class Meta:
        model = UserProject
        fields = ['demo_url', 'sourcecode_url', 'note']

    def clean_demo_url(self):
        url = self.cleaned_data['demo_url']
        if self.instance.require_demo_url and not url:
            raise ValidationError('URL Proyek harus diisi')
        return url

    def clean_sourcecode_url(self):
        url = self.cleaned_data['sourcecode_url']
        if self.instance.require_sourcecode_url and not url:
            raise ValidationError('URL kode sumber proyek harus diisi')
        return url

    def submit_review(self):
        """
        A shortcut to set `status` to Pending Review and save the project.
        Returns Boolean whether status changed or not
        """
        if self.instance.status >= UserProject.STATUS_PENDING_REVIEW:
            self.save()
            return False

        user_project = self.save(commit=False)
        user_project.status = UserProject.STATUS_PENDING_REVIEW
        user_project.save()
        return True

upkoding/projects/views/project.py
import copy
from django.http import HttpResponseRedirect
from django.http.response import Http404, HttpResponse, HttpResponseBadRequest, HttpResponseForbidden, JsonResponse
from django.urls import reverse
from django.views.generic import ListView, DetailView
from django.shortcuts import get_object_or_404
from django.contrib import messages
from django.db import transaction

from account.models import User
from projects.models import Project, UserProject, UserProjectEvent
from projects.forms import UserProjectReviewRequestForm


class ProjectList(ListView):
    paginate_by = 12

    def get_queryset(self):
        search_query = self.request.GET.get('s')
        if search_query:
            return Project.objects.search(search_query)
        return Project.objects.active()

    def get_context_data(self, **kwargs):
        search_query = self.request.GET.get('s')
        page = self.request.GET.get('page')

        data = super().get_context_data(**kwargs)
        data['search_query'] = search_query
        # only show featured project on page 1 AND not in search page
        if not search_query and (not page or page == '1'):
            data['featured_projects'] = Project.objects.featured()
        return data


class ProjectDetail(DetailView):
    def get_object(self):
        """
        We need to find object by using `pk` and `slug`.
        """
        user = self.request.user
        obj = get_object_or_404(
            Project,
            pk=self.kwargs.get('pk'),
            slug=self.kwargs.get('slug'),
        )
        # - allow staff to preview inactive project
        # - or if its active
        if user.is_staff or obj.is_active():
            return obj
        raise Http404()

    def get(self, request, *args, **kwargs):
        if request.GET.get('me') == 'true':
            if not request.user.is_authenticated:
                return HttpResponseForbidden()

            project = self.get_object()
            user_project = get_object_or_404(
                UserProject, user=request.user, project=project)
            return JsonResponse({
                'status': user_project.status,
                'color_class': user_project.get_color_class()
            })
        return super().get(request, *args, **kwargs)

    def post(self, request, slug, pk):
        user = request.user
        project = self.get_object()

        next_url = reverse('projects:detail', args=[slug, pk])
        # not authenticated, ask for login
        if not user.is_authenticated:
            messages.warning(
                request,
                'Silahkan login terlebih dahulu sebelum mengerjakan proyek.',
                extra_tags='warning'
            )
            return HttpResponseRedirect(reverse('account:login') + '?next={}'.format(next_url))

        # assign user to the project
        with transaction.atomic():
            user_project, created = project.assign_to(user)
            if created:
                user_project.add_event(UserProjectEvent.TYPE_PROJECT_START)
                messages.info(request,
                              "Selamat mengerjakan `{}`!".format(
                                  project.title),
                              extra_tags='success')
            success_url = reverse('projects:detail_user', args=[
                slug, pk, user.username])
            return HttpResponseRedirect(success_url)


class ProjectDetailUser(DetailView):
    template_name = 'projects/project_detail_user.html'

    def get_object(self):
        """
        We need to find object by using `pk` and `slug`.
        """
        return get_object_or_404(
            Project,
            pk=self.kwargs.get('pk'),
            slug=self.kwargs.get('slug'),
            status=Project.STATUS_ACTIVE
        )

    def get_context_data(self, **kwargs):
        user = get_object_or_404(User, username=self.kwargs.get('username'))
        user_project = get_object_or_404(
            UserProject, user=user, project=self.object)

        data = super().get_context_data(**kwargs)
        data['user_project'] = user_project

        # show completion form only when:
        # - requirements completed
        # - url has `?form=1`
        # - current user is the owner
        rev_request = self.request.GET.get('form') == '1'
        show_rr_form = user_project.is_requirements_complete() \
            and rev_request \
            and (user == self.request.user)

        if show_rr_form:
            data['rr_form'] = UserProjectReviewRequestForm(
                instance=user_project)
        return data

    def __handle_update(self, request, project, user_project):
        """
        Handle requirements status changes.
        """
        redirect_url = reverse('projects:detail_user', args=[
            project.slug, project.pk, request.user.username])

        # deepcopy to preserve the original state
        requirements = copy.deepcopy(user_project.requirements)
        max_progress = user_project.requirements_completed_percent_max

        if requirements:
            # create a copy and modify this instead so we can compare it later
            requirements_copy = copy.deepcopy(requirements)

            # update requirements_copy
            updated_reqs = map(lambda r: int(r),
                               request.POST.getlist('reqs', []))

            # remove `complete` flag
            for r in requirements_copy:
                if r.get('complete'):
                    del r['complete']

            # assign new flag from `updated_reqs`
            for index in updated_reqs:
                req = requirements_copy[index]
                req['complete'] = True

            # save changes
            user_project.requirements = requirements_copy
            user_project.calculate_progress()
            user_project.save()

            # if all requirements completed, ready for review
            if user_project.is_requirements_complete():
                user_project.add_event(UserProjectEvent.TYPE_PROGRESS_COMPLETE)
                messages.info(request,
                              "Mantap! Proyek kamu siap untuk direview. Klik tombol `Minta Review`",
                              extra_tags='success')
            else:
                _, progress_after, become_complete, _ = UserProject.requirements_diff(
                    requirements, requirements_copy)
                # only create progress update event when progress_after > progress_before
                if progress_after > float(max_progress):
                    for msg in become_complete:
                        user_project.add_event(
                            UserProjectEvent.TYPE_PROGRESS_UPDATE, message=msg)

        return HttpResponseRedirect(redirect_url)

    def __handle_review_request(self, request, project, user_project):
        form = UserProjectReviewRequestForm(
            request.POST, instance=user_project)

        if form.is_valid():
            review_requested = form.submit_review()
            if review_requested:
                user_project.add_event(UserProjectEvent.TYPE_REVIEW_REQUEST)
                messages.info(request,
                              "Great job! Proyek kamu sudah disubmit untuk direview team UpKoding.",
                              extra_tags='success')
            else:
                messages.info(request,
                              "Detail proyek berhasil diupdate!",
                              extra_tags='success')
            return HttpResponse()
        return HttpResponseBadRequest(form.errors.as_json(), content_type='application/json; charset=utf-8')

    def post(self, request, slug, pk, username):
        user = request.user
        request_kind = request.POST.get('kind')
        project_url = reverse('projects:detail', args=[slug, pk])

        # not loggedin?
        if (not user.is_authenticated):
            return HttpResponseRedirect(project_url)

        project = self.get_object()
        user_project = get_object_or_404(
            UserProject, user=user, project=project)

        if request_kind == 'update':
            return self.__handle_update(request, project, user_project)

        if request_kind == 'delete':
            user_project.delete()
            messages.info(request,
                          "Proyek `{}` telah dibatalkan :(".format(
                              project.title),
                          extra_tags='warning')
            return HttpResponse()

        if request_kind == 'review_request':
            return self.__handle_review_request(request, project, user_project)
        return HttpResponseRedirect(project_url)

upkoding/projects/views/review.py
import json
from django.http.response import HttpResponseForbidden, JsonResponse
from django.contrib.auth.mixins import LoginRequiredMixin
from django.views.generic import DetailView
from django.db import transaction

from projects.models import UserProject, UserProjectEvent


class ProjectReview(LoginRequiredMixin, DetailView):
    model = UserProject

    def post(self, request, *args, **kwargs):
        user_project = self.get_object()

        # payload
        data = json.loads(request.body)
        message = data.get('message', '')
        action = data.get('action', '')

        owner = user_project.user
        current_user = request.user

        # only owner and staff can write message to project timeline
        if action == 'message' and ((current_user == owner) or current_user.is_staff):
            user_project.add_event(
                UserProjectEvent.TYPE_REVIEW_MESSAGE,
                user=current_user,
                message=message)
            return JsonResponse({'ok': True})

        # staff can approve projects, but staff project need to be approved by admin :)
        if action == 'approve' and user_project.approvable_by(current_user):
            with transaction.atomic():
                user_project.status = UserProject.STATUS_COMPLETE
                user_project.save()

                # add point to user
                owner.add_point(user_project.point)

                # increment completed count on project
                project = user_project.project
                project.inc_completed_count()

                user_project.add_event(
                    UserProjectEvent.TYPE_PROJECT_COMPLETE,
                    user=current_user,
                    message=message)
                return JsonResponse({'ok': True})

        # only superuser can disapprove (drop the status back to pending review) approved project
        if action == 'disapprove' and current_user.is_superuser:
            was_complete = user_project.is_complete()

            with transaction.atomic():
                user_project.status = UserProject.STATUS_PENDING_REVIEW
                user_project.save()

                # withdraw point and counter if it was approved
                if was_complete:
                    owner.remove_point(user_project.point)

                    # decrement completed count on project
                    project = user_project.project
                    project.dec_completed_count()

                user_project.add_event(
                    UserProjectEvent.TYPE_PROJECT_INCOMPLETE,
                    user=current_user,
                    message=message)
                return JsonResponse({'ok': True})

        return HttpResponseForbidden()

upkoding/projects/templates/projects/templatetags/timeline/avatar.html
{% load base %}
<a href="{{ u.get_absolute_url }}" class="avatar" title="{{ u.get_display_name }}">
    <img src="{{ u|avatar_url:50}}" height="25" width="25" class="rounded-circle" alt="avatar" />
</a>

upkoding/projects/templates/projects/templatetags/timeline/review_form.html
<div class="card text-dark bg-light">
    <div class="card-header">
        {% if fullmode %}Review Form{% else %}Pesan{% endif %}
    </div>
    {% if fullmode %}
    <ul class="list-group list-group-flush">
        {% if user_project.demo_url %}
        <li class="list-group-item">Demo: <a href="{{ user_project.demo_url }}" target="_blank" class="project-url">
                {{ user_project.demo_url }}
            </a>
        </li>
        {% endif %}
        {% if user_project.sourcecode_url %}
        <li class="list-group-item">Kode Sumber: <a href="{{ user_project.sourcecode_url }}" target="_blank"
                class="project-url">
                {{ user_project.sourcecode_url }}
            </a>
        </li>
        {% endif %}
        {% if user_project.note %}
        <li class="list-group-item">{{ user_project.note|linebreaks }}</li>
        {% endif %}
    </ul>
    {% endif %}
    <div class="card-body pt-3 pb-2 ps-3 pe-3" x-data="reviewForm()">

        <div class="mb-3">
            {% if fullmode %}
            <label for="message" class="form-label">Pesan</label>
            {% endif %}
            <textarea class="form-control" id="message" rows="3" placeholder="Tulis pesan disini..."
                x-model="message"></textarea>
        </div>
        <div class="alert"
            :class="{'alert-warning': alert.type=='client', 'alert-danger': alert.type=='server', 'alert-success': alert.type=='success'}"
            role="alert" x-show="alert.type" x-text="alert.message"></div>
        <div class="row mb-2">
            <div class="col col-6">
                {% if not user_project.is_complete and user.is_staff and user != user_project.user %}
                <button type="button" class="btn btn-success" @click="approve"
                    x-html="loading == 'approve' ? spinner : 'Approve'"></button>
                {% endif %}
                {% if user_project.is_complete and user.is_superuser %}
                <button type="button" class="btn btn-danger" @click="disapprove"
                    x-html="loading == 'disapprove' ? spinner : 'Disapprove'"></button>
                {% endif %}
            </div>
            <div class="col col-6">
                <button type="button" class="btn btn-primary float-end" @click="sendMessage"
                    x-html="loading == 'message' ? spinner : 'Kirim Pesan'"></button>
            </div>
        </div>
    </div>
</div>
<script type="text/javascript">
    window.reviewForm = function () {
        return {
            spinner: '<span class="spinner-grow spinner-grow-sm" role="status" aria-hidden="true"></span> Loading...',
            loading: null,
            alert: { type: null, message: '' },
            message: '',
            showAlert(type, message) {
                this.alert = { type: type, message: message }
            },
            resetAlert() {
                this.alert = { type: null, message: '' }
            },
            _post(data, callback) {
                fetch("{% url 'projects:review' user_project.pk %}", {
                    method: 'post',
                    headers: { 'x-CSRFToken': window.csrftoken, 'Content-Type': 'application/javascript' },
                    body: JSON.stringify(data)
                })
                    .then(resp => {
                        if (!resp.ok) {
                            throw Error(resp.statusText)
                        }
                        callback()
                        window.location.reload()
                    })
                    .catch(err => {
                        this.showAlert('server', err)
                    })
                    .finally(() => {
                        this.loading = null
                    })
            },
            approve() {
                if (this.loading) return;
                this.loading = 'approve'
                const payload = { message: this.message, action: 'approve' }

                this._post(payload, () => {
                    this.message = ''
                    this.showAlert('success', 'Proyek telah disetujui!')
                })
            },
            disapprove() {
                if (this.loading) return;
                if (this.message.trim().length == 0) {
                    return this.showAlert('client', 'Berikan alasan kenapa proyek ini batal disetujui!')
                }

                this.loading = 'disapprove'
                const payload = { message: this.message, action: 'disapprove' }

                this._post(payload, () => {
                    this.message = ''
                    this.showAlert('success', 'Proyek telah batal disetujui!')
                })
            },
            sendMessage() {
                if (this.loading) return;
                if (this.message.trim().length == 0) {
                    return this.showAlert('client', 'Pesan tidak boleh kosong!')
                }

                this.loading = 'message'
                const payload = { message: this.message, action: 'message' }
                this._post(payload, () => {
                    this.message = ''
                    this.showAlert('success', 'Pesan dikirim!')
                })
            },
        }
    }
</script>

upkoding/projects/templates/projects/templatetags/timeline/type_0.html
{% load humanize %}
<div class="card">
    <div class="card-body pt-2 pb-2 ps-3 pe-3">
        <span class="float-end d-inline-block ps-2 created">
            {{ event.obj.created|naturaltime }}
        </span>
        <div class="title">
            <a href="{{ event_user.get_absolute_url }}" title="{{ event_user.get_display_name }}">
                <strong>
                    {{ event_user.username }}
                </strong>
            </a>
            {% if event_user.is_staff %}
            <span class="badge bg-secondary ms-1" style="font-size: 10px; font-weight: 300;">STAFF</span>
            {% endif %}
            memulai proyek.
        </div>
    </div>
</div>

upkoding/projects/templates/projects/templatetags/timeline/type_1.html
{% load humanize %}
<div class="card">
    <div class="card-body pt-2 pb-2 ps-3 pe-3">
        <span class="float-end d-inline-block ps-2 created">
            {{ event.obj.created|naturaltime }}
        </span>
        <div class="title">
            <a href="{{ event_user.get_absolute_url }}" title="{{ event_user.get_display_name }}">
                <strong>
                    {{ event_user.username }}
                </strong>
            </a>
            {% if event_user.is_staff %}
            <span class="badge bg-secondary ms-1" style="font-size: 10px; font-weight: 300;">STAFF</span>
            {% endif %}
            menyelesaikan <strong>{{ object.message|truncatewords:5 }}</strong>.
        </div>
    </div>
</div>

upkoding/projects/templates/projects/templatetags/timeline/type_10.html
{% load humanize %}
{% load martortags %}
<div class="card">
    <div class="card-header">
        <a href="{{ event_user.get_absolute_url }}" title="{{ event_user.get_display_name }}">
            {{ event_user.username }}
        </a>
        {% if event_user.is_staff %}
        <span class="badge bg-secondary ms-1" style="font-size: 10px; font-weight: 300;">STAFF</span>
        {% endif %}
        <span class="float-end d-inline-block ps-2 created">
            {{ object.created|naturaltime }}
        </span>
    </div>
    <div class="card-body pt-3 pb-1 ps-3 pe-3">
        {{ object.message|safe_markdown }}
    </div>
</div>

upkoding/projects/templates/projects/templatetags/timeline/type_11.html
{% load humanize %}
{% load martortags %}
<div class="card border-success">
    <div class="card-header">
        <a href="{{ event_user.get_absolute_url }}" title="{{ event_user.get_display_name }}">
            {{ event_user.username }}
        </a>
        <span class="badge bg-success ms-1" style="font-size: 10px; font-weight: 300;">STAFF</span> - <span
            class="text-success">Approved!</span>
        <span class="float-end d-inline-block ps-2 created">
            {{ object.created|naturaltime }}
        </span>
    </div>
    <div class="card-body pt-3 pb-1 ps-3 pe-3">
        {{ object.message|safe_markdown }}
    </div>
</div>

upkoding/projects/templates/projects/templatetags/timeline/type_12.html
{% load humanize %}
{% load martortags %}
<div class="card border-danger">
    <div class="card-header">
        <a href="{{ event_user.get_absolute_url }}" title="{{ event_user.get_display_name }}">
            {{ event_user.username }}
        </a>
        <span class="badge bg-danger ms-1" style="font-size: 10px; font-weight: 300;">STAFF</span>
        <span class="float-end d-inline-block ps-2 created">
            {{ event.obj.created|naturaltime }}
        </span>
    </div>
    <div class="card-body pt-3 pb-1 ps-3 pe-3">
        {{ event.obj.message|safe_markdown }}
    </div>
</div>

upkoding/projects/templates/projects/templatetags/timeline/type_13.html
<div class="card">
    <div class="card-body p-2">
        <div class="title">
            <strong>ekaputra07</strong></a> menyelesaikan Menyelesaikan membuat akun github
        </div>
    </div>
</div>

upkoding/projects/templates/projects/templatetags/timeline/type_2.html
{% load humanize %}
<div class="card">
    <div class="card-body pt-2 pb-2 ps-3 pe-3">
        <span class="float-end d-inline-block ps-2 created">
            {{ event.obj.created|naturaltime }}
        </span>
        <div class="title">
            <a href="{{ event_user.get_absolute_url }}" title="{{ event_user.get_display_name }}">
                <strong>
                    {{ event_user.username }}
                </strong>
            </a>
            {% if event_user.is_staff %}
            <span class="badge bg-secondary ms-1" style="font-size: 10px; font-weight: 300;">STAFF</span>
            {% endif %}
            menyelesaikan semua tasks.
        </div>
    </div>
</div>

upkoding/projects/templates/projects/templatetags/timeline/type_3.html
{% load humanize %}
<div class="card border-warning bg-light">
    <div class="card-body pt-2 pb-2 ps-3 pe-3">
        <span class="float-end d-inline-block ps-2 created">
            {{ event.obj.created|naturaltime }}
        </span>
        <div class="title">
            <a href="{{ event_user.get_absolute_url }}" title="{{ event_user.get_display_name }}">
                <strong>
                    {{ event_user.username }}
                </strong>
            </a>
            {% if event_user.is_staff %}
            <span class="badge bg-secondary ms-1" style="font-size: 10px; font-weight: 300;">STAFF</span>
            {% endif %}
            meminta untuk direview.
            <ul class="list-group mt-3 mb-2">
                {% if user_project.demo_url %}
                <li class="list-group-item">Demo: <a href="{{ user_project.demo_url }}" target="_blank"
                        class="project-url">
                        {{ user_project.demo_url }}
                    </a>
                </li>
                {% endif %}
                {% if user_project.sourcecode_url %}
                <li class="list-group-item">Kode Sumber: <a href="{{ user_project.sourcecode_url }}" target="_blank"
                        class="project-url">
                        {{ user_project.sourcecode_url }}
                    </a>
                </li>
                {% endif %}
                {% if user_project.note %}
                <li class="list-group-item">{{ user_project.note|linebreaks }}</li>
                {% endif %}
            </ul>
        </div>
    </div>
</div>